[package]
name = "sys-auxv"
version = "0.1.0"
edition = "2021"

[features]
default = ["auxvec"]

auxvec = []
glibc = []
rtld = ["glibc"]

[dependencies]
cfg-if = { version = "1.0.0" }

[dev-dependencies]
libc = { version = "0.2.153" }

[[example]]
name = "auxv"
crate-type = ["staticlib"]
