[package]
name = "init"
version = "0.1.0"
edition = "2021"

[features]
default = ["auxvec"]

auxvec = []
esoteric = []

[dependencies]
cfg-if = { version = "1.0.0" }

[dev-dependencies]
libc = { version = "0.2.153" }
